/* Local development config.
 *
 * On the deployed site this file is GENERATED by the ingest workflow, so you do not
 * edit it to go live. It sets dataBase to "./data/out" because the snapshots ship
 * inside the same GitHub Pages deployment as the pages themselves, which means there
 * is no cross-origin fetch and therefore no CORS to configure or to fail silently.
 *
 * apiBase comes from the repo variable SERAPHIM_API_BASE (Settings > Secrets and
 * variables > Actions > Variables).
 *
 * Leave both null here: locally the pages fall back to ../data/out and a localhost
 * API, so `python3 -m http.server` keeps working with no setup.
 */
window.SERAPHIM = {
  dataBase: null,
  apiBase: null,
};
