/* Local development config.
 *
 * On the deployed site this file is GENERATED by the ingest workflow, so you never
 * edit it to go live. It sets dataBase to "./data/out" because the snapshots ship
 * inside the same GitHub Pages deployment as the pages, which means there is no
 * cross-origin fetch and therefore no CORS to configure or to fail silently.
 *
 * Leave it null here: locally the pages fall back to ../data/out, so
 * `python3 -m http.server` keeps working with no setup.
 */
window.SERAPHIM = {
  dataBase: null,
};
